// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSTdGj6XIUlJl8-tDtgGs4DE5cqkCRPF0',
    appId: '1:651349045040:web:a1c0968e37fa9390bd22f5',
    messagingSenderId: '651349045040',
    projectId: 'divya-path-new-app',
    authDomain: 'divya-path-new-app.firebaseapp.com',
    storageBucket: 'divya-path-new-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmFiyjBRqvFq5bVqLuBkNyg70FKnf6Tg',
    appId: '1:651349045040:android:56384f1d007f7c7ebd22f5',
    messagingSenderId: '651349045040',
    projectId: 'divya-path-new-app',
    storageBucket: 'divya-path-new-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFSvgAuFAK333GCBu_IY4bqtbhJM8dKU',
    appId: '1:651349045040:ios:e405c1bc0748655dbd22f5',
    messagingSenderId: '651349045040',
    projectId: 'divya-path-new-app',
    storageBucket: 'divya-path-new-app.firebasestorage.app',
    iosBundleId: 'com.example.divyaPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFSvgAuFAK333GCBu_IY4bqtbhJM8dKU',
    appId: '1:651349045040:ios:e405c1bc0748655dbd22f5',
    messagingSenderId: '651349045040',
    projectId: 'divya-path-new-app',
    storageBucket: 'divya-path-new-app.firebasestorage.app',
    iosBundleId: 'com.example.divyaPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSTdGj6XIUlJl8-tDtgGs4DE5cqkCRPF0',
    appId: '1:651349045040:web:89b55a7e17d814fdbd22f5',
    messagingSenderId: '651349045040',
    projectId: 'divya-path-new-app',
    authDomain: 'divya-path-new-app.firebaseapp.com',
    storageBucket: 'divya-path-new-app.firebasestorage.app',
  );
}
